#
# Makefile for the avmnet infrastructure core modules
# Copyright (C) 2011 AVM GmbH <fritzbox_info@avm.de>
#

obj-$(CONFIG_VR9)	+= ifx/
obj-$(CONFIG_AR9)	+= ifx/
obj-$(CONFIG_AR10)	+= ifx/
obj-$(CONFIG_ATH79) += atheros/
obj-$(CONFIG_MACH_ATHEROS) += atheros/
obj-$(CONFIG_AVMNET_VLAN_MASTER) += vlan_master/
#obj-$(CONFIG_ARCH_QCOM)	+= akronite/

