#
# Makefile for the avmnet infrastructure core modules
# Copyright (C) 2016 AVM GmbH <fritzbox_info@avm.de>
#

avmnet_includes := ../../../include/avmnet_module.h ../../../include/avmnet_config.h

obj-y	+= vlan_master.o

