#
# Makefile for the avmnet infrastructure core modules
# Copyright (C) 2011 AVM GmbH <fritzbox_info@avm.de>
#

avmnet_includes := ../../../include/avmnet_module.h ../../../include/avmnet_config.h

obj-y	+= atheros_gmac.o atheros_mac.o

