#
# Makefile for the avmnet infrastructure core modules
# Copyright (C) 2011 AVM GmbH <fritzbox_info@avm.de>
#

avmnet_includes := ../../../include/avmnet_module.h ../../../include/avmnet_config.h

obj-y	+= mac_ar9.o swi_ar9.o 

obj-m	+= ifxmips_ppa_datapath_ar9_a5.o 
obj-m	+= ifxmips_ppa_hal_ar9_a5.o 