#
# Makefile for the avmnet infrastructure core modules
# Copyright (C) 2011 AVM GmbH <fritzbox_info@avm.de>
#

avmnet_includes := ../../../include/avmnet_module.h ../../../include/avmnet_config.h


obj-m	+= ifxmips_ppa_datapath_vr9_e5.o 
obj-m	+= ifxmips_ppa_datapath_vr9_a5.o 

obj-m	+= ifxmips_ppa_hal_vr9_e5.o
obj-m	+= ifxmips_ppa_hal_vr9_a5.o